### PR TITLE
Drop CircleCI

### PR DESCRIPTION
**Pull request by ab77**
Removes CircleCI

* uses balenaCI to build both `master` and `no-systemd` tags
* https://github.com/product-os/balena-concourse/pull/578
* https://github.com/product-os/scripts/pull/129

Change-type: patch

### CODE REVIEW

**Review by Page- — COMMENTED** [review]
@ab77 the balenaCI build is failing because it's trying to push `balena/open-balena-base:no-systemd:latest`

**Comment by ab77** [comment]
> @ab77 the balenaCI build is failing because it's trying to push `balena/open-balena-base:no-systemd:latest`

Yep, I have a look and it requires some changes to the docker shell scripts in Concourse to do selective replace of `:` to `-` for image variants.

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@Page- can you sanity check this for me please? The concourse changes are in and I've disabled CircleCI builds for this project. balenaCI should be able to build both tags now.

**Review by Page- — APPROVED** [review]

**Pull request merged**
